# Generated by Django 4.2.11 on 2024-04-09 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('waddlewait_app', '0001_initial'),
        ('waddlewaitMenu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('staff_name', models.CharField(default='', max_length=255)),
                ('request_status', models.BooleanField(default=False)),
                ('table_id', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('bill', models.DecimalField(decimal_places=2, max_digits=10)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waddlewait_app.table')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('is_preparing', models.BooleanField(default=False)),
                ('is_ready', models.BooleanField(default=False)),
                ('item_made_time', models.DateTimeField(null=True)),
                ('wait_staff_assigned_time', models.DateTimeField(null=True)),
                ('wait_staff_assigned', models.CharField(default='none', max_length=255)),
                ('deliver', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waddlewaitMenu.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
    ]