# Generated by Django 4.2.11 on 2024-04-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('table_number', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('table_in_use', models.BooleanField(blank=True)),
                ('seats_max', models.IntegerField(blank=True)),
                ('seats_in_use', models.IntegerField(blank=True)),
            ],
        ),
    ]
